# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: CatLib For ILRuntime
author: CatLib
timezone: UTC

# URL
## If your site is put in a subdirectory, set url as 'https://seed.catlib.io/child' and root as '/child/'
url: https://ilruntime.catlib.io
root: /

# Writing
relative_link: false

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: ../node_modules/hexo-theme-cookbook

ignore:
  - '**/node_modules/**/*node_modules'

cookbook:
  favicon: favicon.ico
  tag:
    anchor:
      default: core
      core: https://github.com/CatLib/Core
  gitment:
    enable: true
    id: ilrt-zh
    client_id: 9756f1c332911548f818
    client_secret: 58f8229fd10d2614488fd7798b737eddbd8f0b68
    github_owner: catlib
    github_repository: ilruntime-zh.io
    cross_server: https://31225080.ap-southeast-1.fc.aliyuncs.com/2016-08-15/proxy/gitment/gitment-cross/
    per_page: 30
    maintainer:
      - yb199478